from django.urls import include, path

from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('employees', views.EmployeeViewset, basename='employee') # This registers the EmployeeViewset with the router. The first argument is the prefix for the URL, the second argument is the viewset class, and the third argument is an optional basename that can be used to specify the base name for the URL patterns generated by the router. If not provided, it will be automatically determined based on the queryset attribute of the viewset.

urlpatterns = [
    path('students/', views.studentsView),
    path('students/<int:pk>', views.studentsDetailView),

    # path('employees/', views.Employees.as_view()), # This as_view() means we are using class based views. It converts the Employees class into a view that can handle HTTP requests.
    # path('employees/<int:pk>', views.EmployeeDetail.as_view()),

    path('', include(router.urls)),
]
